# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7eb8640f1bdc8eb6b57915b7192cc9fba10416c3deeadc1423f05dbb324192743cfdc9e226cbda6e45037fd5f3db81d4f09ab631683bbdec958295e57f852f96

test:
  secret_key_base: ff615c27096679fdbae6a39f0da3109493d3e24aaf6ff7f8b38052069c36b3805d6472d17da8012c2574ef3803a151ee452bd404bf2c6d56afdc85452275011b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
